### ISSUE TITLE
刚发布的1.5版本是不是有错误?

### ISSUE THREAD

**Issue by tsingsun** [polarismesh/polaris-go#155]
**Describe the bug**

接收到1.5版本的提醒,但测试未通过:

https://github.com/tsingsun/woocoo/pull/270

```
panic: assignment to entry in nil map

goroutine 56 [running]:
github.com/polarismesh/polaris-go/pkg/flow.(*WatchEngine).addInstanceWatchContext(...)
	/home/runner/go/pkg/mod/github.com/polarismesh/polaris-go@v1.5.0/pkg/flow/watch_flow.go:256
github.com/polarismesh/polaris-go/pkg/flow.(*WatchEngine).notifyAllInstances(0xc000100dc0, 0xc0001af770)
	/home/runner/go/pkg/mod/github.com/polarismesh/polaris-go@v1.5.0/pkg/flow/watch_flow.go:283 +0x23b
github.com/polarismesh/polaris-go/pkg/flow.(*WatchEngine).WatchAllInstances(0xd324a0?, 0xc0000e1a20?)
	/home/runner/go/pkg/mod/github.com/polarismesh/polaris-go@v1.5.0/pkg/flow/watch_flow.go:249 +0x25
github.com/polarismesh/polaris-go/pkg/flow.(*Engine).WatchAllInstances(0xc0001af770?, 0xc0000e1a20?)
	/home/runner/go/pkg/mod/github.com/polarismesh/polaris-go@v1.5.0/pkg/flow/sync_flow.go:637 +0x25
github.com/polarismesh/polaris-go/api.(*consumerAPI).WatchAllInstances(0xc0000e1a20, 0xc0001af770)
	/home/runner/go/pkg/mod/github.com/polarismesh/polaris-go@v1.5.0/api/consumer_impl.go:124 +0x7f
github.com/tsingsun/woocoo/contrib/polarismesh.(*polarisNamingResolver).Watch(0xc0002c5680)
	/home/runner/work/woocoo/woocoo/contrib/polarismesh/resolver.go:169 +0x22b
created by github.com/tsingsun/woocoo/contrib/polarismesh.(*resolverBuilder).Build
	/home/runner/work/woocoo/woocoo/contrib/polarismesh/resolver.go:58 +0x311
FAIL	github.com/tsingsun/woocoo/contrib/polarismesh	2.022s
```
assignment to entry in nil map是flow报错的, 麻烦确认一下.

**Comment by houseme** [comment]
这里修复了，https://github.com/polarismesh/polaris-go/pull/154

**Comment by houseme** [comment]
https://github.com/polarismesh/polaris-go/pull/154 这里应该是修复了，可以试试最新的

**Comment by tsingsun** [comment]
tag的问题.包括github desktop都没有更新到最新的commit.
<img width="924" alt="image" src="https://github.com/polarismesh/polaris-go/assets/5848549/8f3c8bf6-afc3-44ae-9849-b6aabb8eccdc">
